version: '3.7'

services:

  httpd:
    image: nginx:latest
    expose:
      - "${HTTPD_LISTEN_PORT}"
    ports:
      - "${HTTPD_LISTEN_PORT}:${HTTPD_LISTEN_PORT}"
    env_file:
      - ./gleipnir/.env
    volumes:
      - ./gleipnir/httpd/nginx.conf:/etc/nginx/nginx.conf
      - ./gleipnir/httpd/upstream.conf:/etc/nginx/upstream.conf
      - ./gleipnir/httpd/m2.conf:/etc/nginx/m2.conf
      - ./gleipnir/httpd/sites:/etc/nginx/sites-available
      - ./gleipnir/ssl/certificates:/etc/nginx/certificates
      - .:/var/www/html
    depends_on:
      - php
      - database

  php:
    build:
      context: ./gleipnir/php/${PHP_VERSION}
      dockerfile: Dockerfile
    ports:
      - "9000"
    user: "${USER}"
    env_file:
      - ./gleipnir/.env
    volumes:
      - ./gleipnir/php/${PHP_VERSION}/conf/php.ini:/usr/local/etc/php/php.ini
      - ./gleipnir/php/${PHP_VERSION}/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./gleipnir/php/${PHP_VERSION}/conf/www.conf:/usr/local/etc/www.conf
      - .:/var/www/html

  database:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${DB_LISTEN_PORT}:${DB_LISTEN_PORT}"
    env_file:
      - ./gleipnir/.env
    expose:
      - "${DB_LISTEN_PORT}"
    volumes:
      - db-persistance:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - redis-persistance:/data

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}-management-alpine
    hostname: ${PROJECT_NAME}-rabbitmq
    env_file:
      - ./gleipnir/.env
    volumes:
        - rabbitmq-persistance:/var/lib/rabbitmq

volumes:
    db-persistance:
      name: ${PROJECT_NAME}-db-data
    rabbitmq-persistance:
      name: ${PROJECT_NAME}-rabbit-data
    redis-persistance:
      name: ${PROJECT_NAME}-redis-data
